version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: agendamentos-db
    environment:
      POSTGRES_USER: user_agendamento
      POSTGRES_PASSWORD: password_agendamento
      POSTGRES_DB: db_agendamento
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: