services:
  db:
    image: postgres:15-alpine
    container_name: agendamentos-db-final
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_agendamento
    ports:
      - "5434:5432"
    volumes:
      - pgdata_novo:/var/lib/postgresql/data

volumes:
  pgdata_novo: